apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: imfd4e1bo-nodejs 
  janus-idp.io/tekton: imfd4e1bo-nodejs
  backstage.io/kubernetes-id: imfd4e1bo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: imfd4e1bo-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml